;;; worker-pool-test.el --- Focused tests for the packaged Anvil worker pool -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'anvil-worker)

(ert-deftest anvil-worker-emacsclient-args-disable-fallback-editors ()
  "Unix and TCP clients must fail closed when their worker endpoint is absent."
  (let ((server-use-tcp nil))
    (should
     (equal (anvil-worker--emacsclient-server-args "/tmp/worker.sock")
            '("-a" "false" "-s" "/tmp/worker.sock"))))
  (let ((server-use-tcp t))
    (should
     (equal (anvil-worker--emacsclient-server-args "/tmp/worker.auth")
            '("-a" "false" "-f" "/tmp/worker.auth")))))

(ert-deftest anvil-worker-health-retries-an-already-dead-worker ()
  "A dead-to-dead health tick retries spawning without logging a transition."
  (let ((worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :last-state 'dead))
        (spawn-count 0)
        logs)
    (cl-letf (((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--quick-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--spawn-worker)
               (lambda (_worker) (cl-incf spawn-count)))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest entry) (push entry logs))))
      (anvil-worker--health-check-one worker))
    (should (= spawn-count 1))
    (should-not logs)
    (should (eq (plist-get worker :last-state) 'dead))))

(ert-deftest anvil-worker-kill-clears-all-owned-and-grace-state ()
  "An intentional pool kill forgets every owned process and spawn grace."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test" :lane :read)))
    (puthash "anvil-worker-read-test" 1.0 anvil-worker--spawn-times)
    (puthash "discarded-worker" 2.0 anvil-worker--spawn-times)
    (puthash "discarded-worker" 'not-a-process anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil)))
      (anvil-worker-kill))
    (should (= (hash-table-count anvil-worker--spawn-times) 0))
    (should (= (hash-table-count anvil-worker--owned-processes) 0))))

(ert-deftest anvil-worker-kill-gracefully-stops-responsive-owned-worker ()
  "A healthy owned worker runs kill-emacs hooks instead of receiving SIGKILL."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (sentinel (make-temp-name
                   (expand-file-name "anvil-worker-cleanup-"
                                     temporary-file-directory)))
        (owned-live t)
        (graceful-calls 0)
        (hard-stop-calls 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (unwind-protect
        (cl-letf (((symbol-function 'anvil-worker--map-pool)
                   (lambda (function) (funcall function worker)))
                  ((symbol-function 'processp)
                   (lambda (process) (eq process owned)))
                  ((symbol-function 'process-live-p)
                   (lambda (process) (and (eq process owned) owned-live)))
                  ((symbol-function 'anvil-worker--worker-alive-p)
                   (lambda (_worker) t))
                  ((symbol-function 'anvil-worker--request-graceful-stop)
                   (lambda (_worker)
                     (cl-incf graceful-calls)
                     (with-temp-file sentinel (insert "clean\n"))
                     (setq owned-live nil)
                     t))
                  ((symbol-function 'anvil-worker--hard-stop-owned)
                   (lambda (_name _process) (cl-incf hard-stop-calls)))
                  ((symbol-function 'anvil-worker--log)
                   (lambda (&rest _args))))
          (anvil-worker-kill)
          (should (file-exists-p sentinel))
          (should (= graceful-calls 1))
          (should (= hard-stop-calls 0))
          (should (= (hash-table-count
                      anvil-worker--owned-processes)
                     0)))
      (when (file-exists-p sentinel)
        (delete-file sentinel)))))

(ert-deftest anvil-worker-graceful-stop-has-a-hard-deadline ()
  "A wedged kill-emacs client is deleted at the configured deadline."
  (let ((anvil-worker-alive-check-timeout 0.25)
        (server-use-tcp nil)
        (worker (list :name "anvil-worker-read-test"
                      :server-file "/tmp/anvil-worker-read-test"))
        (stop-process 'stop-process)
        (now 0.0)
        (stop-live t)
        (accept-count 0)
        (delete-count 0)
        logs)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args)
                 (should (equal (plist-get args :command)
                                '("emacsclient" "-a" "false" "-s"
                                  "/tmp/anvil-worker-read-test"
                                  "-e" "(kill-emacs)")))
                 stop-process))
              ((symbol-function 'float-time)
               (lambda (&optional _time) now))
              ((symbol-function 'process-live-p)
               (lambda (process)
                 (and (eq process stop-process) stop-live)))
              ((symbol-function 'accept-process-output)
               (lambda (process &rest _args)
                 (should (eq process stop-process))
                 (cl-incf accept-count)
                 (cl-incf now 0.1)))
              ((symbol-function 'delete-process)
               (lambda (process)
                 (should (eq process stop-process))
                 (cl-incf delete-count)
                 (setq stop-live nil)))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest entry) (push entry logs))))
      (should-not (anvil-worker--request-graceful-stop worker)))
    (should (= delete-count 1))
    (should (<= accept-count 3))
    (should (= (cl-count 'stop-timeout logs :key #'car) 1))))

(ert-deftest anvil-worker-graceful-stop-error-cleans-client-and-hard-stops ()
  "An error in the graceful wait deletes its client before hard fallback."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (server-use-tcp nil)
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (stop-client 'stop-client)
        (owned-live t)
        (stop-client-live t)
        (client-deletes 0)
        (hard-stops 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) t))
              ((symbol-function 'processp)
               (lambda (process) (memq process (list owned stop-client))))
              ((symbol-function 'process-live-p)
               (lambda (process)
                 (cond ((eq process owned) owned-live)
                       ((eq process stop-client) stop-client-live))))
              ((symbol-function 'make-process)
               (lambda (&rest _args) stop-client))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _args) (error "injected wait failure")))
              ((symbol-function 'delete-process)
               (lambda (process)
                 (should (eq process stop-client))
                 (cl-incf client-deletes)
                 (setq stop-client-live nil)))
              ((symbol-function 'anvil-worker--hard-stop-owned)
               (lambda (name process)
                 (should-not stop-client-live)
                 (should (equal name "anvil-worker-read-test"))
                 (should (eq process owned))
                 (cl-incf hard-stops)
                 (setq owned-live nil)
                 (remhash name anvil-worker--owned-processes)
                 t))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest _args))))
      (anvil-worker-kill))
    (should (= client-deletes 1))
    (should (= hard-stops 1))
    (should-not stop-client-live)
    (should-not owned-live)))

(ert-deftest anvil-worker-hard-stop-confirms-owned-worker-is-dead ()
  "The hard fallback retains no ownership after SIGKILL is observed."
  (let ((anvil-worker--owned-processes (make-hash-table :test #'equal))
        (owned 'owned-process)
        (owned-live t)
        (kill-count 0))
    (puthash "anvil-worker-read-test" owned anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'process-live-p)
               (lambda (process) (and (eq process owned) owned-live)))
              ((symbol-function 'kill-process)
               (lambda (process)
                 (should (eq process owned))
                 (cl-incf kill-count)
                 (setq owned-live nil))))
      (should (anvil-worker--hard-stop-owned
               "anvil-worker-read-test" owned)))
    (should (= kill-count 1))
    (should-not owned-live)
    (should-not (gethash "anvil-worker-read-test"
                         anvil-worker--owned-processes))))

(ert-deftest anvil-worker-kill-hard-stops-unresponsive-owned-worker ()
  "An owned worker that cannot answer the full probe is hard-killed."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (owned-live t)
        (graceful-calls 0)
        (hard-kills 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'processp)
               (lambda (process) (eq process owned)))
              ((symbol-function 'process-live-p)
               (lambda (process) (and (eq process owned) owned-live)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--request-graceful-stop)
               (lambda (_worker) (cl-incf graceful-calls)))
              ((symbol-function 'anvil-worker--hard-stop-owned)
               (lambda (name process)
                 (should (equal name "anvil-worker-read-test"))
                 (should (eq process owned))
                 (cl-incf hard-kills)
                 (setq owned-live nil)
                 (remhash name anvil-worker--owned-processes)
                 t))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest _args))))
      (anvil-worker-kill))
    (should (= graceful-calls 0))
    (should (= hard-kills 1))))

(ert-deftest anvil-worker-kill-falls-back-after-post-probe-wedge ()
  "A worker wedged after its probe gets bounded grace, then SIGKILL."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (owned-live t)
        (graceful-calls 0)
        (hard-kills 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'processp)
               (lambda (process) (eq process owned)))
              ((symbol-function 'process-live-p)
               (lambda (process) (and (eq process owned) owned-live)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) t))
              ((symbol-function 'anvil-worker--request-graceful-stop)
               (lambda (_worker)
                 (cl-incf graceful-calls)
                 nil))
              ((symbol-function 'anvil-worker--hard-stop-owned)
               (lambda (name process)
                 (should (equal name "anvil-worker-read-test"))
                 (should (eq process owned))
                 (cl-incf hard-kills)
                 (setq owned-live nil)
                 (remhash name anvil-worker--owned-processes)
                 t))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest _args))))
      (anvil-worker-kill))
    (should (= graceful-calls 1))
    (should (= hard-kills 1))
    (should-not owned-live)
    (should (= (hash-table-count anvil-worker--owned-processes) 0))))

(ert-deftest anvil-worker-kill-retains-live-worker-after-failed-hard-stop ()
  "A graceful client exit never releases a still-live owned worker."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (graceful-calls 0)
        (hard-stop-calls 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'processp)
               (lambda (process) (eq process owned)))
              ((symbol-function 'process-live-p)
               (lambda (process) (eq process owned)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) t))
              ((symbol-function 'anvil-worker--request-graceful-stop)
               (lambda (_worker)
                 (cl-incf graceful-calls)
                 t))
              ((symbol-function 'anvil-worker--hard-stop-owned)
               (lambda (_name _process)
                 (cl-incf hard-stop-calls)
                 nil))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest _args))))
      (anvil-worker-kill))
    (should (= graceful-calls 1))
    (should (= hard-stop-calls 1))
    (should (eq (gethash "anvil-worker-read-test"
                         anvil-worker--owned-processes)
                owned))))

(ert-deftest anvil-worker-kill-blocks-timer-respawn-during-graceful-wait ()
  "A health tick cannot respawn or discard ownership during pool shutdown."
  (let ((anvil-worker--kill-in-progress nil)
        (anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (server-use-tcp nil)
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :last-state 'alive
                      :server-file "/tmp/anvil-worker-read-test"))
        (owned 'owned-process)
        (replacement 'replacement-process)
        (stop-client 'stop-client)
        (owned-live t)
        (stop-client-live t)
        (health-ticks 0)
        (spawn-timers 0)
        (spawn-count 0))
    (puthash "anvil-worker-read-test" owned
             anvil-worker--owned-processes)
    (cl-letf (((symbol-function 'anvil-worker--map-pool)
               (lambda (function) (funcall function worker)))
              ((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) owned-live))
              ((symbol-function 'processp)
               (lambda (process)
                 (memq process (list owned replacement stop-client))))
              ((symbol-function 'process-live-p)
               (lambda (process)
                 (cond ((eq process owned) owned-live)
                       ((eq process replacement) t)
                       ((eq process stop-client) stop-client-live))))
              ((symbol-function 'make-process)
               (lambda (&rest _args) stop-client))
              ((symbol-function 'accept-process-output)
               (lambda (process &rest _args)
                 (should (eq process stop-client))
                 (should anvil-worker--kill-in-progress)
                 (cl-incf health-ticks)
                 (setq owned-live nil)
                 ;; Timers run inside accept-process-output.  Exercise both
                 ;; the repeating health callback and deferred pool/worker
                 ;; spawn callbacks.
                 (anvil-worker--health-check)
                 (anvil-worker-spawn)
                 (anvil-worker--spawn-worker worker)
                 ;; Identity-checked cleanup must also preserve a replacement
                 ;; mapping even if another callback registered one directly.
                 (puthash "anvil-worker-read-test" replacement
                          anvil-worker--owned-processes)
                 (setq stop-client-live nil)))
              ((symbol-function 'start-process)
               (lambda (&rest _args)
                 (cl-incf spawn-count)
                 replacement))
              ((symbol-function 'run-at-time)
               (lambda (&rest _args) (cl-incf spawn-timers)))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest _args))))
      (anvil-worker-kill))
    (should (= health-ticks 1))
    (should (= spawn-timers 0))
    (should (= spawn-count 0))
    (should (eq (plist-get worker :last-state) 'alive))
    (should (eq (gethash "anvil-worker-read-test"
                         anvil-worker--owned-processes)
                replacement))
    (should-not anvil-worker--kill-in-progress)))

(ert-deftest anvil-worker-quick-check-documents-the-direct-probe ()
  "The packaged documentation must describe its patched liveness mechanism."
  (should (string-match-p
           "direct connect probe on the cached socket path"
           (documentation 'anvil-worker--quick-alive-p)))
  (should-not (string-search
               "file + PID only, no probe"
               (documentation 'anvil-worker--spawn-worker))))

(ert-deftest anvil-worker-spawn-grace-does-not-slide ()
  "A suppressed spawn must not extend the grace window forever."
  (let ((anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (anvil-worker-init-file "/tmp/anvil-worker-test-init.el")
        (anvil-worker-spawn-grace 45)
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :server-file "/tmp/anvil-worker-read-test"))
        (now 0.0)
        (spawn-count 0))
    (unwind-protect
        (cl-letf (((symbol-function 'float-time)
                   (lambda (&optional _time) now))
                  ((symbol-function 'anvil-worker--quick-alive-p)
                   (lambda (_worker) nil))
                  ((symbol-function 'start-process)
                   (lambda (&rest _args)
                     (cl-incf spawn-count)
                     (intern (format "fake-process-%d" spawn-count))))
                  ((symbol-function 'set-process-query-on-exit-flag)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'process-id)
                   (lambda (_process) 4242))
                  ((symbol-function 'anvil-worker--maybe-schedule-warmup)
                   (lambda (_worker) nil))
                  ((symbol-function 'anvil-worker--log)
                   (lambda (&rest _entry) nil)))
          (anvil-worker--spawn-worker worker)
          (should (= spawn-count 1))
          (should (= (gethash "anvil-worker-read-test"
                              anvil-worker--spawn-times)
                     0.0))
          (setq now 10.0)
          (anvil-worker--spawn-worker worker)
          (should (= spawn-count 1))
          (should (= (gethash "anvil-worker-read-test"
                              anvil-worker--spawn-times)
                     0.0))
          (setq now 50.0)
          (anvil-worker--spawn-worker worker)
          (should (= spawn-count 2))
          (should (= (gethash "anvil-worker-read-test"
                              anvil-worker--spawn-times)
                     50.0)))
      (let ((buffer (get-buffer " *anvil-worker-read-test*")))
        (when buffer (kill-buffer buffer))))))

(ert-deftest anvil-worker-health-kills-owned-hung-worker-at-threshold ()
  "Only the third idle failed full probe kills an owned connectable worker."
  (let* ((anvil-worker-hung-check-limit 3)
         (anvil-worker--spawn-times (make-hash-table :test #'equal))
         (anvil-worker--owned-processes (make-hash-table :test #'equal))
         (worker (list :name "anvil-worker-read-test"
                       :lane :read
                       :busy nil
                       :hung-checks 0
                       :last-state 'alive))
         (owned 'owned-process)
         (quick-alive t)
         (kill-count 0)
         (spawn-count 0)
         logs)
    (puthash "anvil-worker-read-test" owned anvil-worker--owned-processes)
    (puthash "anvil-worker-read-test" 1.0 anvil-worker--spawn-times)
    (cl-letf (((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--quick-alive-p)
               (lambda (_worker) quick-alive))
              ((symbol-function 'processp)
               (lambda (process) (eq process owned)))
              ((symbol-function 'process-live-p)
               (lambda (process) (eq process owned)))
              ((symbol-function 'process-id)
               (lambda (_process) 4242))
              ((symbol-function 'kill-process)
               (lambda (_process) (cl-incf kill-count)))
              ((symbol-function 'anvil-worker--spawn-worker)
               (lambda (_worker) (cl-incf spawn-count)))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest entry) (push entry logs))))
      (anvil-worker--health-check-one worker)
      (anvil-worker--health-check-one worker)
      (should (= kill-count 0))
      (anvil-worker--health-check-one worker)
      (should (= kill-count 1))
      (should (= spawn-count 0))
      (should-not (gethash "anvil-worker-read-test"
                           anvil-worker--owned-processes))
      (should-not (gethash "anvil-worker-read-test"
                           anvil-worker--spawn-times))
      (setq quick-alive nil)
      (anvil-worker--health-check-one worker)
      (should (= spawn-count 1))
      (should (= (cl-count 'unresponsive logs :key #'car) 1))
      (should (= (cl-count 'hung-killed logs :key #'car) 1)))))

(ert-deftest anvil-worker-health-never-kills-a-busy-worker ()
  "A busy worker's slow event loop is owned by dispatch, not health checks."
  (let ((anvil-worker-hung-check-limit 1)
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :busy t
                      :hung-checks 0
                      :last-state 'alive))
        (terminate-count 0))
    (cl-letf (((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--quick-alive-p)
               (lambda (_worker) t))
              ((symbol-function 'anvil-worker--terminate-owned-hung-worker)
               (lambda (_worker) (cl-incf terminate-count))))
      (dotimes (_ 4) (anvil-worker--health-check-one worker)))
    (should (= terminate-count 0))
    (should (= (plist-get worker :hung-checks) 0))
    (should (eq (plist-get worker :last-state) 'alive))))

(ert-deftest anvil-worker-health-logs-unowned-hung-worker-once ()
  "A connectable worker not spawned by this Emacs is never killed by PID."
  (let ((anvil-worker-hung-check-limit 1)
        (anvil-worker--spawn-times (make-hash-table :test #'equal))
        (anvil-worker--owned-processes (make-hash-table :test #'equal))
        (worker (list :name "anvil-worker-read-test"
                      :lane :read
                      :busy nil
                      :hung-checks 0
                      :last-state 'alive))
        logs)
    (cl-letf (((symbol-function 'anvil-worker--worker-alive-p)
               (lambda (_worker) nil))
              ((symbol-function 'anvil-worker--quick-alive-p)
               (lambda (_worker) t))
              ((symbol-function 'anvil-worker--log)
               (lambda (&rest entry) (push entry logs))))
      (anvil-worker--health-check-one worker)
      (anvil-worker--health-check-one worker))
    (should (= (cl-count 'hung-unowned logs :key #'car) 1))
    (should (plist-get worker :hung-unowned-logged))))

;;; worker-pool-test.el ends here
