#!/bin/bash

if [[ -f package.yaml ]]; then
   hpack
fi

cabal2nix . > default.nix
# cabal2nix --shell . > shell.nix

cabal clean
nix-shell --command 'cabal configure --enable-tests --enable-benchmarks'
