#!/bin/bash

cabal=$(echo *.cabal)

if [[ ! -f default.nix ]]; then
    cabal2nix . > default.nix
fi

if [[ ! -f Setup.hs && ! -f Setup.lhs ]]; then
    cat > Setup.hs <<EOF
import Distribution.Simple
main = defaultMain
EOF
fi

nix-build "$@" -E 'let pkgs = import <nixpkgs> {}; in pkgs.stdenv.lib.callPackageWith (pkgs // pkgs.haskell-ng.packages.ghc763) ./default.nix {}'
