#!/bin/bash

cabal=$(echo *.cabal)

profiling=no
if [[ "$1" == "prof" ]]; then
    profiling=yes
    shift 1
fi

if [[ ! -f default.nix ]]; then
    cabal2nix . > default.nix
fi

if [[ ! -f Setup.hs && ! -f Setup.lhs ]]; then
    cat > Setup.hs <<EOF
import Distribution.Simple
main = defaultMain
EOF
fi

if [[ $profiling == yes ]]; then
    nix-build "$@" -E 'let pkgs = import <nixpkgs> {}; in pkgs.stdenv.lib.callPackageWith (pkgs // pkgs.profiledHaskell7102Packages) ./default.nix {}'
else
    nix-build "$@" -E 'let pkgs = import <nixpkgs> {}; in pkgs.stdenv.lib.callPackageWith (pkgs // pkgs.haskell7102Packages) ./default.nix {}'
fi
