#!/bin/bash

cabal=$(echo *.cabal)

if [[ ! -f default.nix ]]; then
    cabal2nix . > default.nix
fi

if [[ ! -f Setup.hs ]]; then
    cat > Setup.hs <<EOF
import Distribution.Simple
main = defaultMain
EOF
fi

nix-shell '<nixpkgs>' -A haskell784Packages.$(basename $(pwd)).env "$@"
