#!/bin/bash

cabal2nix . > default.nix
cabal2nix --shell . > shell.nix

if [[ -d .git ]]; then
    if ! grep -q /default.nix .git/info/exclude; then
        echo /default.nix >> .git/info/exclude
    fi
    if ! grep -q /shell.nix .git/info/exclude; then
        echo /shell.nix >> .git/info/exclude
    fi
