#!/bin/bash -xe

name=$1
shift 1

git stash --keep-index

tg create tg/$name origin/master

cat > .topmsg <<EOF
From: John Wiegley <johnw@newartisans.com>
Subject: [PATCH] $*
EOF

git add .topmsg
git commit -m create
tg export $name
git push -f -u jwiegley $name

open https://github.com/jwiegley/nixpkgs

git co master
git cp $name && git branch -D $name
git stash pop
