#!/bin/bash -e

if [[ "$1" == "-a" ]]; then
    shift 1

    if [[ "$1" == "-p" ]]; then
        shift 1
        cd ~/.nix-defexpr/nixpkgs-next
        git remote update
        git pull && git pull --tags
        git gc && git prune
    fi

    nix-env -f '<nixpkgs-next>' -u "$@"
    rsync -a --delete ~/.nix-defexpr/nixpkgs-next/ ~/.nix-defexpr/nixpkgs/
    git --git-dir=$HOME/.nix-defexpr/nixpkgs/.git push --mirror jwiegley
    copy-nix hermes --leq -Q -j4
else
    nix-env -q | sed 's/-[0-9].*//' | xargs nix-env -f '<nixpkgs>' -u "$@"
fi
