pkgs: epkgs: with epkgs;
[
  ace-jump-mode
  ace-link
  ace-mc
  ace-window
  adoc-mode
  agda2-mode                    # agda2-mode agda-input
  aggressive-indent
  alert
  anaphora
  anki-editor
  apiwrap
  aria2
  ascii
  asoc
  async
  auctex                        # auctex latex
  auto-yasnippet
  avy
  avy-zap
  backup-each-save
  backup-walker
  bats-mode
  beacon
  biblio
  bm
  bookmark-plus                 # bookmark+
  bufler
  browse-at-remote
  browse-kill-ring
  browse-kill-ring-plus         # browse-kill-ring+
  button-lock
  bytecomp-simplify
  calfw
  calfw-cal
  calfw-org
  cargo
  cell-mode
  centered-cursor-mode
  change-inner
  chess                         # chess chess-ics
  circe
  clipmon
  cmake-font-lock
  cmake-mode
  col-highlight
  color-moccur
  color-theme
  command-log-mode
  company
  company-auctex
  company-cabal
  company-coq
  company-ghc
  company-lsp
  company-math
  company-nixos-options
  company-quickhelp
  company-restclient
  company-terraform
  copy-as-format
  counsel
  counsel-gtags
  counsel-jq
  counsel-osx-app
  counsel-projectile
  counsel-tramp
  crosshairs
  crux
  csv-mode
  ctable
  cursor-chg
  debbugs                       # debbugs-gnu
  deadgrep
  dedicated
  deferred
  deft
  diff-hl                       # diff-hl diff-hl-flydiff
  diffview
  diminish
  dired-plus
  dired-ranger
  dired-toggle
  diredful
  direnv
  discover-my-major
  docker
  docker-compose-mode
  docker-tramp
  dockerfile-mode
  doxymacs
  dumb-jump
  ebdb                          # ebdb-com
  edbi
  edit-env
  edit-indirect
  edit-server
  edit-var
  eglot
  el-mock
  elisp-depend
  elisp-docstring-mode
  elisp-refs
  elisp-slime-nav
  elmacro
  emamux
  # emms                          # emms-setup
  emojify
  engine-mode
  enh-ruby-mode                 # ruby-mode
  # ensime
  epc
  epl
  erc-highlight-nicknames
  erc-yank
  erefactor
  es-mode
  eshell-bookmark
  eshell-up
  eshell-z
  esxml
  eval-expr
  eval-in-repl
  evil
  expand-region
  eyebrowse
  f
  fancy-narrow
  fast-scroll
  feebleline
  fence-edit
  fennel-mode
  fetchmail-mode
  fill-page
  flycheck
  flycheck-haskell
  flycheck-hdevtools
  flycheck-package
  flycheck-rust
  fn
  focus
  font-lock-studio
  forge
  format-all
  free-keys
  fringe-helper
  fullframe
  fuzzy
  ggtags
  # ghc-mod                       # ghc
  ghub
  ghub-plus                     # ghub+
  git-annex
  git-link
  git-timemachine
  git-undo
  gitattributes-mode
  gitconfig-mode
  gitignore-mode
  github-review
  gitpatch
  gnus-alias
  gnus-harvest
  gnus-recent
  google-this
  goto-last-change
  goto-line-preview
  graphviz-dot-mode
  gud-lldb
  haskell-mode
  hcl-mode
  helm
  helm-aws
  helm-bibtex                   # ivy-bibtex
  helm-descbinds
  helm-describe-modes
  helm-firefox
  helm-google
  helm-navi
  helm-org-rifle
  helpful
  highlight
  highlight-cl
  highlight-defined
  highlight-numbers
  hl-line-plus                  # hl-line+
  ht
  hydra
  ialign
  iedit
  iflipb
  imenu-list
  indent-shift
  info-lookmore
  initsplit
  ipcalc
  ivy
  ivy-compile
  ivy-explorer
  ivy-hydra
  ivy-pass
  ivy-rich
  jobhours
  jq-format
  jq-mode
  js2-mode
  js3-mode
  json-mode
  json-reformat
  json-snatcher
  key-chord
  keypression
  know-your-http-well
  kubernetes
  kv
  language-detection
  langtool
  ledger-mode
  # lentic                        # lentic-mode
  link-hint
  lispy
  list-utils
  lively
  #llvm-mode
  load-time
  logito
  loop
  lsp-haskell
  lsp-mode
  lsp-ui
  lua-mode
  m-buffer
  macrostep
  magit
  magit-annex
  magit-imerge
  magit-lfs
  magit-popup
  magit-tbdiff
  makefile-runner
  makey
  malyon
  markdown-mode
  markdown-preview-mode
  marshal
  math-symbol-lists
  mc-calc
  mc-extras                     # mc-extras mc-freeze mc-rect
  mediawiki
  memory-usage
  message-x
  mic-paren
  minimap
  mmm-mode
  moccur-edit
  monitor
  multi-term
  multifiles
  multiple-cursors
  muse
  names
  navi-mode
  nf-procmail-mode
  nginx-mode
  nix-buffer
  nix-mode
  nix-sandbox
  nixos-options
  # nixpkgs-fmt
  noflet
  nov
  oauth2
  ob-diagrams
  ob-sql-mode
  ob-restclient
  ob-rust
  olivetti
  operate-on-number
  origami
  org                           # org org-babel org-crypt
  org-bookmark-heading
  org-gcal
  org-jira
  org-mind-map
  org-noter
  org-opml
  # org-pdfview
  org-pdftools
  org-ref
  org-rich-yank
  org-super-agenda
  org-web-tools
  orgit
  orgnav
  orgtbl-aggregate
  origami
  outorg
  outshine
  ov
  ovpn-mode
  ox-extra
  ox-gfm
  ox-pandoc
  ox-texinfo-plus
  ox-slack
  package-lint
  packed
  pandoc-mode
  paradox
  paredit
  parent-mode
  parsebib
  parsec
  parse-csv
  pass
  password-store
  pcre2el
  pdf-tools
  per-window-point
  persistent-scratch
  peval
  pfuture
  phi-search
  phi-search-mc
  pkg-info
  plantuml-mode
  # po-mode
  popup
  popup-pos-tip
  popup-ruler
  popwin
  pos-tip
  posix-manual
  pp-c-l
  prodigy
  projectile
  pretty-hydra
  proof-general                 # proof-site
  python-mode
  racer
  rainbow-delimiters
  rainbow-mode
  redshank
  regex-tool
  repl-toggle
  request
  restclient
  reveal-in-osx-finder
  rich-minority
  riscv-mode
  rs-gnus-summary
  rust-auto-use
  rust-mode
  s
  sbt-mode
  scala-mode
  sdcv-mode
  selected
  separedit
  shackle
  shell-toggle
  shift-number
  simple-httpd
  sky-color-clock
  slidify-pages
  slime
  smart-mode-line
  smart-newline
  smartparens                   # smartparens-config
  smartscan
  smex
  sort-words
  spinner
  springboard
  sql-indent
  stopwatch
  string-edit
  string-inflection
  super-save
  supercite
  swiper
  tablegen-mode
  tablist
  tagedit
  terraform-mode
  tidy
  tla-mode
  transpose-mark
  treemacs
  tuareg
  typo
  undo-propose
  unicode-fonts
  use-package
  uuidgen
  vagrant
  vagrant-tramp
  vdiff
  verb
  vimish-fold
  visual-fill-column
  visual-regexp
  virtual-auto-fill
  vline
  w3m
  wat-mode
  web
  web-beautify
  web-mode
  web-server
  websocket
  wgrep
  which-key
  whitespace-cleanup-mode
  window-purpose
  with-editor
  word-count-mode               # word-count
  worf
  x86-lookup
  xml-rpc
  xr
  xray
  yaml-mode
  yankpad
  yaoddmuse
  yari-with-buttons             # yari
  yasnippet
  z3-mode
  zoom
  zoutline
  ztree                         # ztree-diff
]
